# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJKIZq1A9I8f3eL59QQppbOpteUyjjbt
"""

import numpy as np
import matplotlib.pyplot as plt

def lagrange_basis(x, x_nodes, i):
    """Calcula o polinomio de base de Lagrange l_i(x)"""
    n = len(x_nodes)
    result = 1.0
    for j in range(n):
        if i != j:
            result = result * (x - x_nodes[j]) / (x_nodes[i] - x_nodes[j])
    return result

def lagrange_interpolation(x_nodes, y_nodes, x_eval):
    """Calcula o polinomio interpolador de Lagrange"""
    n = len(x_nodes)
    if isinstance(x_eval, (int, float)):
        p_x = 0.0
        for i in range(n):
            p_x = p_x + y_nodes[i] * lagrange_basis(x_eval, x_nodes, i)
        return p_x
    else:
        p_x = np.zeros(len(x_eval))
        for i in range(n):
            basis_vals = np.array([lagrange_basis(x, x_nodes, i) for x in x_eval])
            p_x = p_x + y_nodes[i] * basis_vals
        return p_x

# Dados
x_nodes = np.array([0.4, 0.52, 0.6])
y_nodes = np.array([0.27, 0.29, 0.32])
x_eval = 0.47

# Calculo
p2_eval = lagrange_interpolation(x_nodes, y_nodes, x_eval)
print(f"p2(0.47) = {p2_eval:.8f}")