# -*- coding: utf-8 -*-
"""Untitled38.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jJKIZq1A9I8f3eL59QQppbOpteUyjjbt
"""

import numpy as np
import matplotlib.pyplot as plt

# Função de base de Lagrange
def lagrange_basis(x, xi, j):
    """
    x: valor onde avaliar
    xi: nós de interpolação (array)
    j: índice do polinômio de base
    """
    num = 1.0
    denom = 1.0
    for m in range(len(xi)):
        if m != j:
            num *= (x - xi[m])
            denom *= (xi[j] - xi[m])
    return num / denom

# Polinômio de Lagrange completo
def lagrange_interpolation(x, xi, yi):
    L = 0.0
    for j in range(len(xi)):
        L += yi[j] * lagrange_basis(x, xi, j)
    return L

# Função Spline Linear
def linear_spline(x, xi, yi):
    # Supõe que xi está ordenado
    for k in range(len(xi)-1):
        if xi[k] <= x <= xi[k+1]:
            # Interpolação linear entre xi[k] e xi[k+1]
            return yi[k] + (yi[k+1] - yi[k]) * ((x - xi[k]) / (xi[k+1] - xi[k]))
    # Fora do intervalo, pode retornar np.nan ou extrapolar
    return np.nan

# Exemplo prático:
# Defina a função a ser interpolada
def f(x):
    return np.sin(x)

xi = np.linspace(0, np.pi, 5) # 5 nós
yi = f(xi)

# Avaliação em pontos para plotar
xx = np.linspace(0, np.pi, 100)
Lx = np.array([lagrange_interpolation(x, xi, yi) for x in xx])
Spline_x = np.array([linear_spline(x, xi, yi) for x in xx])
fx = f(xx)

# Erro
erro_lagrange = np.abs(Lx - fx)
erro_spline = np.abs(Spline_x - fx)

# Gráfico
plt.figure(figsize=(10,6))
plt.plot(xx, fx, 'k-', label='Função Original')
plt.plot(xx, Lx, 'r--', label='Interpolação Lagrange')
plt.plot(xx, Spline_x, 'b-.', label='Spline Linear')
plt.plot(xi, yi, 'go', label='Nós de Interpolação')
plt.legend()
plt.title('Interpolação Polinomial (Lagrange) e Spline Linear')
plt.xlabel('x')
plt.ylabel('y')
plt.grid(True)
plt.show()

# Resumo do erro
print('Erro máximo (Lagrange):', np.max(erro_lagrange))
print('Erro máximo (Spline Linear):', np.max(erro_spline))