# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbMeUtJyroPchHmMnsl9WJwR2PMUP7CW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

def rk2_method(f, x0, y0, h, x_final):
    n = int((x_final - x0) / h)
    x = np.linspace(x0, x0 + n*h, n + 1)
    y = np.zeros(n + 1)
    y[0] = y0
    for i in range(n):
        k1 = f(x[i], y[i])
        k2 = f(x[i] + h, y[i] + h * k1)
        y[i + 1] = y[i] + (h / 2) * (k1 + k2)
    return x, y

def f(x, y):
    return 0.04 * y

def solucao_analitica(x):
    return 1000 * np.exp(0.04 * x)

x0, y0, x_final = 0, 1000, 1
h_values = [1, 0.5, 0.25, 0.1]
y_true = solucao_analitica(x_final)

print(f"Solução analítica: y(1) = {y_true:.6f}\n")

for h in h_values:
    x, y = rk2_method(f, x0, y0, h, x_final)
    erro = abs(y[-1] - y_true)
    print(f"h = {h:<5} | y(1) ≈ {y[-1]:.6f} | Erro = {erro:.2e}")

# Gráficos
plt.figure(figsize=(12, 5))

plt.subplot(1, 2, 1)
x_analitica = np.linspace(0, 1, 100)
y_analitica = solucao_analitica(x_analitica)
for h in h_values:
    x, y = rk2_method(f, x0, y0, h, x_final)
    plt.plot(x, y, 'o-', label=f'h={h}')
plt.plot(x_analitica, y_analitica, 'k--', linewidth=2, label='Analítica')
plt.title('RK2 - Comparação de Soluções')
plt.xlabel('x')
plt.ylabel('y(x)')
plt.legend()
plt.grid(True, alpha=0.3)

plt.subplot(1, 2, 2)
h_vals, erros = [], []
for h in h_values:
    x, y = rk2_method(f, x0, y0, h, x_final)
    h_vals.append(h)
    erros.append(abs(y[-1] - y_true))
plt.loglog(h_vals, erros, 'ro-', linewidth=2, markersize=8)
plt.title('Taxa de Convergência (RK2)')
plt.xlabel('h')
plt.ylabel('Erro em y(1)')
plt.grid(True, alpha=0.3, which='both')

plt.tight_layout()
plt.show()