# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbMeUtJyroPchHmMnsl9WJwR2PMUP7CW
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Método de Euler
def euler_method(f, x0, y0, h, x_final):
    n = int((x_final - x0) / h)
    x = np.linspace(x0, x0 + n*h, n + 1)
    y = np.zeros(n + 1)
    y[0] = y0
    for i in range(n):
        y[i + 1] = y[i] + h * f(x[i], y[i])
    return x, y

# Método de Runge-Kutta 2ª ordem
def rk2_method(f, x0, y0, h, x_final):
    n = int((x_final - x0) / h)
    x = np.linspace(x0, x0 + n*h, n + 1)
    y = np.zeros(n + 1)
    y[0] = y0
    for i in range(n):
        k1 = f(x[i], y[i])
        k2 = f(x[i] + h, y[i] + h * k1)
        y[i + 1] = y[i] + (h / 2) * (k1 + k2)
    return x, y

# Solução analítica
def solucao_analitica(x):
    return 1000 * np.exp(0.04 * x)

# Função diferencial
def f(x, y):
    return 0.04 * y

# Parâmetros
x0, y0, x_final = 0, 1000, 1
h_values = [1, 0.5, 0.25, 0.1]

# Calcular solução analítica
y_true = solucao_analitica(x_final)
x_analitica = np.linspace(x0, x_final, 1000)
y_analitica = solucao_analitica(x_analitica)

print("Solução Analítica em x=1:", y_true)

# Tabela resumida
dados = []
for h in h_values:
    x_e, y_e = euler_method(f, x0, y0, h, x_final)
    x_r, y_r = rk2_method(f, x0, y0, h, x_final)

    erro_e = abs(y_e[-1] - y_true)
    erro_r = abs(y_r[-1] - y_true)

    dados.append({
        'h': h,
        'Passos': len(x_e) - 1,
        'y_Euler': y_e[-1],
        'Erro_Euler': erro_e,
        'y_RK2': y_r[-1],
        'Erro_RK2': erro_r,
        'Razao': erro_e / erro_r if erro_r > 0 else np.inf
    })

df = pd.DataFrame(dados)
print("\nTabela de Convergência:")
print(df.to_string(index=False))

# Gráficos
fig, axes = plt.subplots(2, 3, figsize=(18, 10))

# Gráfico 1: Euler vs Analítica
ax = axes[0, 0]
for h in h_values:
    x, y = euler_method(f, x0, y0, h, x_final)
    ax.plot(x, y, 'o-', label=f'h={h}', markersize=4)
ax.plot(x_analitica, y_analitica, 'k--', linewidth=2, label='Analítica')
ax.set_xlabel('x')
ax.set_ylabel('y(x)')
ax.set_title('Euler vs Analítica')
ax.legend()
ax.grid(True, alpha=0.3)

# Gráfico 2: RK2 vs Analítica
ax = axes[0, 1]
for h in h_values:
    x, y = rk2_method(f, x0, y0, h, x_final)
    ax.plot(x, y, 's-', label=f'h={h}', markersize=4)
ax.plot(x_analitica, y_analitica, 'k--', linewidth=2, label='Analítica')
ax.set_xlabel('x')
ax.set_ylabel('y(x)')
ax.set_title('RK2 vs Analítica')
ax.legend()
ax.grid(True, alpha=0.3)

# Gráfico 3: Comparação para h=0.1
ax = axes[0, 2]
h_best = 0.1
x_e, y_e = euler_method(f, x0, y0, h_best, x_final)
x_r, y_r = rk2_method(f, x0, y0, h_best, x_final)
ax.plot(x_e, y_e, 'bo-', label='Euler', markersize=4, alpha=0.7)
ax.plot(x_r, y_r, 'gs-', label='RK2', markersize=4, alpha=0.7)
ax.plot(x_analitica, y_analitica, 'k--', linewidth=2, label='Analítica')
ax.set_xlabel('x')
ax.set_ylabel('y(x)')
ax.set_title(f'Comparação h={h_best}')
ax.legend()
ax.grid(True, alpha=0.3)

# Gráfico 4: Erro Euler
ax = axes[1, 0]
for h in h_values:
    x, y = euler_method(f, x0, y0, h, x_final)
    erro = np.abs(y - solucao_analitica(x))
    ax.semilogy(x, erro, 'o-', label=f'h={h}', markersize=4)
ax.set_xlabel('x')
ax.set_ylabel('Erro Absoluto')
ax.set_title('Erro Euler')
ax.legend()
ax.grid(True, alpha=0.3, which='both')

# Gráfico 5: Erro RK2
ax = axes[1, 1]
for h in h_values:
    x, y = rk2_method(f, x0, y0, h, x_final)
    erro = np.abs(y - solucao_analitica(x))
    ax.semilogy(x, erro, 's-', label=f'h={h}', markersize=4)
ax.set_xlabel('x')
ax.set_ylabel('Erro Absoluto')
ax.set_title('Erro RK2')
ax.legend()
ax.grid(True, alpha=0.3, which='both')

# Gráfico 6: Convergência
ax = axes[1, 2]
h_vals = [d['h'] for d in dados]
erros_e = [d['Erro_Euler'] for d in dados]
erros_r = [d['Erro_RK2'] for d in dados]
ax.loglog(h_vals, erros_e, 'bo-', linewidth=2, markersize=8, label='Euler')
ax.loglog(h_vals, erros_r, 'gs-', linewidth=2, markersize=8, label='RK2')
ax.set_xlabel('h')
ax.set_ylabel('Erro em y(1)')
ax.set_title('Taxa de Convergência')
ax.legend()
ax.grid(True, alpha=0.3, which='both')

plt.tight_layout()
plt.savefig('comparacao.png', dpi=300, bbox_inches='tight')
plt.show()