# -*- coding: utf-8 -*-
"""Untitled37.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pbMeUtJyroPchHmMnsl9WJwR2PMUP7CW
"""

import numpy as np
import matplotlib.pyplot as plt

# Definição do método de Euler Explícito
def euler_method(f, x0, y0, h, x_final):
    """
    Método de Euler Explícito para resolução de PVI
    Parâmetros:
      f : função f(x, y)
      x0: valor inicial de x
      y0: valor inicial de y
      h : passo
      x_final: valor final de x
    Retorna:
      x, y - arrays com pontos calculados
    """
    n = int((x_final - x0) / h)
    x = np.linspace(x0, x0 + n*h, n+1)
    y = np.zeros(n+1)
    y[0] = y0
    for i in range(n):
        y[i+1] = y[i] + h * f(x[i], y[i])
    return x, y

# Função diferencial f(x, y) = 0.04 * y
def f(x, y):
    return 0.04 * y

# Solução analítica
def solucao_analitica(x):
    return 1000 * np.exp(0.04 * x)

# Parâmetros iniciais
x0 = 0
y0 = 1000
x_final = 1
h_values = [1, 0.5, 0.25, 0.1]

# Calcular solução analítica para referência
y_true = solucao_analitica(x_final)
print(f"Solução analítica em x=1: y(1) = {y_true:.6f}")

# Resultados e gráficos
plt.figure(figsize=(8,5))

for h in h_values:
    x, y = euler_method(f, x0, y0, h, x_final)
    erro = abs(y[-1] - y_true)
    print(f"h = {h:<5} | y(1) ≈ {y[-1]:.6f} | Erro = {erro:.2e}")
    plt.plot(x, y, marker='o', label=f'Euler h={h}')

# Solução analítica para muitos pontos
x_analitica = np.linspace(x0, x_final, 100)
y_analitica = solucao_analitica(x_analitica)
plt.plot(x_analitica, y_analitica, label='Solução Analítica', color='black', linewidth=2)
plt.title('Método de Euler vs. Solução Analítica')
plt.xlabel('x')
plt.ylabel('y')
plt.legend()
plt.grid(True)
plt.show()